sudo: required

services:
  - docker

language: generic

env:
- DISTRI=ubuntu DESKTOP=xfce
- DISTRI=ubuntu DESKTOP=icewm
- DISTRI=centos DESKTOP=xfce
- DISTRI=centos DESKTOP=icewm

script:
  - docker build -t local/${DISTRI}-${DESKTOP}-vnc -f ./Dockerfile.${DISTRI}.${DESKTOP}.vnc .
after_success:
  - bash .build/trigger_dockerhub.sh ${DISTRI}-${DESKTOP}-vnc

notifications:
  email:
    recipients:
      - "Sakuli%0032%0062%0032Notifications+719bb1d7615904fb214c668723655875@zulip.consol.de"
    on_success: always # default: change
    on_failure: always # default: always
